id: P005636
initial_creation_type: ocr
source_metadata:
  id: bdr:W21847
  title: མདོ་མཁྱེན་བརྩེ་ཡེ་ཤེས་རྡོ་རྗེའི་རྣམ་ཐར
  author: ''
  volumes:
    d864c91649b642aa99ca5da2b7b45bcc:
      image_group_id: I4236
      title: ''
      volume_number: 1
      total_pages: 328
